# -*- coding: utf-8 -*-
"""Examen 1 - IA 354

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uez47-6Qf5DsVGAgZAiklSYfBEPSPCH3
"""

import pandas as pd
df = pd.read_csv("/content/sample_data/amzn_raw_data.csv")

df

"""#**Ejercico 2**

**Media**
"""

import numpy
import pandas as pd
from scipy import stats

media1 = numpy.mean(df['open'])
print("La media de Open es: ",media1)

media2 = numpy.mean(df['high'])
print("La media de High es: ",media2)

media3 = numpy.mean(df['low'])
print("La media de Low es: ",media3)

media4 = numpy.mean(df['close'])
print("La media de Close es: ",media4)

media5 = numpy.mean(df['volume'])
print("La media de Volume es: ",media5)

media6 = numpy.mean(df['adjusted_close'])
print("La media de adjusted_close es: ",media6)

media7 = numpy.mean(df['change_percent'])
print("La media de change_percent es: ",media7)

media8 = numpy.mean(df['avg_vol_20d'])
print("La media de avg_vol_20d es: ",media8)

"""  **Moda**"""

moda = stats.mode(df['open'])
print("La moda de Open es: ", moda)

moda = stats.mode(df['high'])
print("La moda de High es: ", moda)

moda = stats.mode(df['low'])
print("La moda de Low es: ", moda)

moda = stats.mode(df['close'])
print("La moda de Close es: ", moda)

moda = stats.mode(df['volume'])
print("La moda de Volume es: ", moda)

moda = stats.mode(df['adjusted_close'])
print("La moda de adjusted_close es: ", moda)

moda = stats.mode(df['change_percent'])
print("La moda de change_percent es: ", moda)

moda = stats.mode(df['avg_vol_20d'])
print("La moda de avg_vol_20d es: ", moda)

"""**Cuartiles**"""

import numpy as np

def cuantiles(lista, q=[25, 50, 75]):
    # Convertimos la lista en un arreglo numpy para facilidad de cálculos
    arr = np.array(lista)

    # Calculamos los cuantiles
    return {f"{quantile}%": np.percentile(arr, quantile) for quantile in q}

# Ejemplo
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(cuantiles(lista))

q=[25, 50, 75]
def cuantiles(lista):
    # Convertimos la lista en un arreglo numpy para facilidad de cálculos
    arr = np.array(lista)

    # Calculamos los cuantiles
    return {f"{quantile}%": np.percentile(arr, quantile) for quantile in q}

# Ejemplo
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(cuantiles(lista))

"""**Percentiles**"""

p = []
for i in range(1, 101):
    p.append(i)

def percentiles(lista):
    # Convertimos la lista en un arreglo numpy para facilidad de cálculos
    arr = np.array(lista)

    # Calculamos los percentiles
    return {f"{percentile}th percentil": np.percentile(arr, percentile) for percentile in p}

# Resultados
print("Percentiles de Open: \n ",percentiles(df['open']))
print("Percentiles de High: \n ",percentiles(df['high']))
print("Percentiles de Low: \n ",percentiles(df['low']))
print("Percentiles de Close: \n ",percentiles(df['close']))
print("Percentiles de Volume: \n ",percentiles(df['volume']))
print("Percentiles de adjusted_close: \n ",percentiles(df['adjusted_close']))
print("Percentiles de change_percent: \n ",percentiles(df['change_percent']))
print("Percentiles de avg_vol_20d: \n ",percentiles(df['avg_vol_20d']))

